#!/bin/bash
#
# tupper - A container image manager
#
# Copyright (c) 2018 Matt Ferris <matt@bueller.ca>
# Licensed under BSD 2-clause license
# github.com/mattferris/tupper/blob/master/License.txt
#

set -e

if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
    echo "error: layer lineage: can't locate common.inc" >&2
    exit 1
fi

. "$TUP_LIB_DIR/includes/common.inc"

trap tup_error ERR


#
# print usage
#
_usage() {
    cat <<EOF

usage: $TUP_FRONT_CMD $(basename $0) <ref> [ --date ] [ --help ] [ --long-id ] [ --reverse ]

Display the lineage of a layer.

Arguments:

    ref        The layer to display the lineage of

    --date     Display the date the layer was created
    --help     Print usage information
    --long-id  Print the full layer ID
    --reverse  Print the lineage in reverse order (oldest to youngest)

EOF
    exit 1
}


#
# parse args
#

tup_getopt_required=(1)
tup_getopt_optional=(date help long-id reverse)
while tup_getopt; do
    case $tup_getopt_name in
        1) ref=$tup_getopt_value ;;
        date) opt_date=1 ;;
        help) _usage ;;
        long-id) opt_long_id=1 ;;
        reverse) opt_reverse=1 ;;
    esac
done

# handle getopt errors
tup_error_getopt

# check for missing required options
if [[ ${#tup_getopt_required[@]} -ge 1 ]]; then
    _usage
fi


#
# check prerequisites
#

if ! layerid=$(tup refparse --layer "$ref"); then
    tup_error 2  "layer lineage: layer doesn't exist: $ref"
fi


#
# main
#

layers=()
while [[ ! -z "$layerid" ]]; do
    layers=(${layers[@]} $layerid)
    layerid=$(tup_conf get layer $layerid parent)
done

print_layer_id() {
    if [[ $opt_long_id = 1 ]]; then
        echo -n $layerid
    else
        echo -n ${layerid:0:12}
    fi
    if [[ $opt_date = 1 ]]; then
        echo -n "  $(tup_conf get layer $layerid date)"
    fi
    echo
}

if [[ $opt_reverse ]]; then
    while [[ ${#layers[@]} -gt 0 ]]; do
        layerid=${layers[${#layers[@]}-1]}
        print_layer_id $layerid
        unset layers[${#layers[@]}-1]
    done
else
    for layerid in ${layers[@]}; do
        print_layer_id $layerid
    done
fi

exit 0
