#!/bin/bash
#
# tupper - A container image manager
#
# Copyright (c) 2018 Matt Ferris <matt@bueller.ca>
# Licensed under BSD 2-clause license
# github.com/mattferris/tupper/blob/master/License.txt
#

set -e

if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
    echo "error: can't locate common.inc" >&2
    exit 1
fi

. "$TUP_LIB_DIR/includes/common.inc"

trap tup_error ERR


#
# print usage
#
_usage() {
    cat <<EOF

usage: $TUP_FRONT_CMD $(basename $0) <ref> [ --help ]

Mount a layer.

Arguments:

    ref     The ID of the layer to mount
    --help  Print usage information

EOF
    exit 1
}


#
# parse args
#

tup_getopt_required=(1)
tup_getopt_optional=(help)
while tup_getopt; do
    case $tup_getopt_name in
        1) ref=$tup_getopt_value ;;
        help) _usage ;;
    esac
done

# handle getopt errors
tup_error_getopt

# check for missing required options
if [[ ${#tup_getopt_required[@]} -ge 1 ]]; then
    _usage
fi


#
# check prerequisites
#

if ! layerid=$(tup refparse "$ref" --type layer); then
    echo "error: layer doesn't exist: $ref" >&2
    exit 2
fi


#
# main
#

if ! format=$(tup_conf get layer "$layerid" format); then
    echo "error: unable to get format of layer: $layerid" >&2
    exit 4
fi

if ! (tup volume mount "$format" "$TUP_STORAGE_DIR/layers/$(tup_path "$layerid")/fs); then
    echo "error: unable to mount layer: $layerid" >&2
    exit 4
fi

echo "mounted layer $layerid"

exit 0
