#!/bin/bash
#
# tupper - A container image manager
#
# Copyright (c) 2018 Matt Ferris <matt@bueller.ca>
# Licensed under BSD 2-clause license
# github.com/mattferris/tupper/blob/master/License.txt
#

set -e

ref=$1
name=$ref

if [[ -z "$name" ]]; then
    echo "usage: $TUP_FRONT_CMD $(basename $0) <ref> [ <target> ]" >&2
    exit 1
fi

target="$TUP_IMGDIR/$name"
if [[ ! -z "$2" ]]; then
    if [[ ! -z "$( echo "$2" | grep ^/ )" ]]; then
        target="$2"
    else
        target="$TUP_IMGDIR/$2"
    fi
fi

ref=$("$TUP_BINDIR/refparse" "$ref")

if [[ ! -d "$TUP_OBJDIR/layers/$ref" ]]; then
    echo "error: object doesn't exist: $name" >&2
    exit 1
fi

if [[ -d "$target" ]]; then
    echo "error: aborting, target already exists" >&2
    exit 1
fi

mkdir "$target"
echo "$ref" > "$target/obj"

echo "created $target based on $ref" >&2
