#!/bin/bash
#
# tupper - A container image manager
#
# Copyright (c) 2018 Matt Ferris <matt@bueller.ca>
# Licensed under BSD 2-clause license
# github.com/mattferris/tupper/blob/master/License.txt
#

set -e

if [[ ! -d "$TUP_IMGDIR" ]]; then
    echo "error: images directory doesn't exist: $TUP_IMGDIR" >&2
    exit 1
fi

ls -1 "$TUP_IMGDIR"
