#!/bin/bash
#
# tupper - A container image manager
#
# Copyright (c) 2018 Matt Ferris <matt@bueller.ca>
# Licensed under BSD 2-clause license
# github.com/mattferris/tupper/blob/master/License.txt
#

set -e

name=$1
ref=$2

if [[ -z "$ref" ]]; then
    echo "usage: $TUP_FRONT_CMD $(basename $0) <name> <ref>" >&2
    exit 1
fi

if [[ ! -d "$TUP_IMGDIR/$name" ]]; then
    echo "error: image doesn't exist: $name" >&2
    exit 1
fi

tref=$("$TUP_BINDIR/refparse" "$ref")
if [[ -z "$tref" ]]; then
    echo "error: bad ref, or object doesn't exist: $ref" >&2
    exit 1
fi

echo "$tref" > "$TUP_IMGDIR/$name/obj"

echo "rebased $name to $tref"
