#!/bin/bash
#
# tupper - A container image manager
#
# Copyright (c) 2018 Matt Ferris <matt@bueller.ca>
# Licensed under BSD 2-clause license
# github.com/mattferris/tupper/blob/master/License.txt
#

set -e

name=$1

if [[ -z "$name" ]]; then
    echo "usage: $TUP_FRONT_CMD $(basename $0) <name>" >&2
    exit 1
fi

path="$TUP_IMGDIR/$name"
if [[ "$( echo $name | grep ^/ )" = "$name" ]]; then
    path="$name"
fi

if [[ ! -d "$path" ]]; then
    echo "error: image doesn't exist: $path" >&2
    exit 1
fi

cd "$path"

if [[ ! -d "fs" ]]; then
    echo "error: nothing to revert: $name" >&2
    exit 1
fi

rm -r "fs"

echo "reverted changes in $name" >&2
