#!/bin/bash
#
# tupper - A container image manager
#
# Copyright (c) 2018 Matt Ferris <matt@bueller.ca>
# Licensed under BSD 2-clause license
# github.com/mattferris/tupper/blob/master/License.txt
#

set -e

name=$1

if [[ -z "$name" ]]; then
    echo "usage: $TUP_FRONT_CMD $(basename $0) <name>" >&2
    exit 1
fi

path="$TUP_IMGDIR/$name"
if [[ "$( echo $name | grep ^/ )" = "$name" ]]; then
    path="$name"
fi

if [[ ! -d "$path" ]]; then
    echo "error: image doesn't exist: $path" >&2
    exit 1
fi

cd "$path"

obj=""
if [[ -f "obj" ]]; then
    obj=$(cat obj)
fi

echo -n "$name "
if [[ ! -z "$obj" && -d "fs" && ! -z "$(ls fs/*)" ]]; then
    echo -n "modified"
else
    echo -n "unmodified"
fi

if [[ ! -z "$obj" ]]; then
    echo -n " since $obj"
fi

echo
