#!/bin/bash
#
# tupper - A container image manager
#
# Copyright (c) 2018 Matt Ferris <matt@bueller.ca>
# Licensed under BSD 2-clause license
# github.com/mattferris/tupper/blob/master/License.txt
#

set -e

name=$1
ref=$2

if [[ -z "$ref" ]]; then
    for ref in $(ls -1 "$TUP_OBJDIR/tags"); do
        echo "$ref -> $("$TUP_BINDIR/refparse" "$(cat "$TUP_OBJDIR/tags/$ref")")"
    done
    exit 0
fi

tref=$("$TUP_BINDIR/refparse" "$ref")
if [[ -z "$tref" ]]; then
    echo "error: ref doesn't exist: $ref"
    exit 1
fi

echo "$tref" > "$TUP_OBJDIR/tags/$name"
