#!/bin/bash
#
# tupper - A container image manager
#
# Copyright (c) 2018 Matt Ferris <matt@bueller.ca>
# Licensed under BSD 2-clause license
# github.com/mattferris/tupper/blob/master/License.txt
#

set -e

if ! [[ -f "$TUP_LIB_DIR/includes/common.inc" ]]; then
    echo "error: can't locate common.inc" >&2
    exit 1
fi

. "$TUP_LIB_DIR/includes/common.inc"

trap tup_error ERR


#
# print usage
#
_usage() {
    cat <<EOF

usage: $TUP_FRONT_CMD $(basename $0) [ <arg> ... ] [ --help ]

Generate a checksum from the supplied arguments. If no arguments are specified
then generate a checksum of the contents of the current directory.

Arguments:

    --help  Print usage information

EOF
    exit 1
fi

tup_getopt_optional=(help)
while tup_getopt; do
    case $tup_getopt_name in
        help) _usage ;;
    esac
done

# handle getopt errors
tup_error_getopt

# check for missing required options
if [[ ${#tup_getopt_required[@]} -ge 1 ]]; then
    _usage
fi


#
# main
#

tup_sum $@

exit 0
