#!/bin/bash
#
# tupper - A container image manager
#
# Copyright (c) 2018 Matt Ferris <matt@bueller.ca>
# Licensed under BSD 2-clause license
# github.com/mattferris/tupper/blob/master/License.txt
#

set -e

name=$1
msg=$2

if [ -z "$name" ]; then
    echo "usage: $(basename $0) <name> [ <msg> ]" >&2
    exit 1
fi

base="/root/containers"

path="$base/img/$name"
if [ "$( echo $name | grep ^/ )" = "$name" ]; then
    path="$name"
fi

if [ ! -d "$path" ]; then
    echo "error: image doesn't exist: $path" >&2
    exit 1
fi

cd "$path"

if [ ! -d "fs" ]; then
    echo "error: nothing to commit: $name" >&2
    exit 1
fi

author="$(whoami)@$(hostname -f)"

fssum=$( cd fs && tar c * | sha1sum | cut -d\  -f1 )
psum=""

if [ -f "obj" ]; then
    psum=$(cat obj)
fi

sum=$( echo "${fssum} ${psum}" | sha1sum | cut -d\  -f1 )

mkdir -p "$base/obj/$sum"
if [ ! -d "$base/ref" ]; then
    mkdir "$base/ref"
fi

mv fs "$base/obj/$fssum"
echo $fssum > "$base/obj/$sum/fs"
echo "$author" > "$base/obj/$sum/author"
echo "$msg" > "$base/obj/$sum/msg"

if [ ! -z "$psum" ]; then
    echo $psum > "$base/obj/$sum/parent"
fi

if [ "$path" = "$base/img/$name" ]; then
    echo $sum > "$base/ref/$name"
fi

echo $sum > "$path/obj"

echo "committed $sum ($name)" >&2
