#!/bin/bash

ref=$1

if [ -z "$ref" ]; then
    echo "usage: $(basename $0) <ref>" >&2
    exit 1
fi

base="/root/containers"

if [ -d "$base/img/$ref" ]; then
    echo $ref
    if [ ! -f "$base/img/$ref/obj" ]; then
        echo "error: image doesn't reference a layer object: $ref" >&2
        exit 1
    fi
    ref=$(cat "$base/img/$ref/obj")
fi

ref=$("$base/ctl/refparse" "$ref")

#
# resolve the chain of parents
#
_resparent() {
    ref=$1

    if [ ! -d "$base/obj/$ref" ]; then
        echo "error: layer object doesn't exist: $ref" >&2
        exit 1
    fi

    cd "$base/obj/$ref"

    echo "$ref <$(cat "$base/obj/$ref/author")> $(cat "$base/obj/$ref/msg")"

    if [ ! -f "parent" ]; then
        return 0
    fi

    parent=$("$base/ctl/refparse" "$(cat parent)")

    if [ ! -d "$base/obj/$parent" ]; then
        echo "error: undefined parent $parent for layer object $ref" >&2
        exit 1
    fi

    _resparent $parent
}

_resparent $ref
