#!/bin/bash
#
# tupper - A container image manager
#
# Copyright (c) 2018 Matt Ferris <matt@bueller.ca>
# Licensed under BSD 2-clause license
# github.com/mattferris/tupper/blob/master/License.txt
#

set -e

name=$1
ref=$2

if [ -z "$ref" ]; then
    echo "usage: $(basename $0) <name> <ref>" >&2
    exit 1
fi

base="/root/containers"

if [ ! -d "$base/img/$name" ]; then
    echo "error: image doesn't exist: $name" >&2
    exit 1
fi

tref=$("$base/ctl/refparse" "$ref")
if [ -z "$tref" ]; then
    echo "error: bad ref, or object doesn't exist: $ref" >&2
    exit 1
fi

echo "$tref" > "$base/img/$name/obj"

echo "rebased $name to $tref"
