#!/bin/bash
#
# tupper - A container image manager
#
# Copyright (c) 2018 Matt Ferris <matt@bueller.ca>
# Licensed under BSD 2-clause license
# github.com/mattferris/tupper/blob/master/License.txt
#

set -e

ref=$1

if [ -z "$ref" ]; then
    echo "usage: $(basename $0) <ref> ..." >&2
    exit 1
fi

base="/root/containers"

for ref in $@; do
    tref=$("$base/ctl/refparse" "$ref")
    if [ -z "$tref" ]; then
        echo "error: ref doesn't exist: $ref" >&2
        exit 1
    fi

    fs=$(cat "$base/obj/$tref/fs")

    rm -r "$base/obj/$fs" "$base/obj/$tref"

    echo "removed $tref"
done
