#!/bin/bash
set -e

ref=$1
ancestor=$2
msg=$3

if [ -z "$ancestor" ]; then
    echo "usage: $(basename $0) <ref> <ancestor> [ <msg> ]" >&2
    exit 1
fi

base="/root/containers"

# cleanup on exit
_cleanup() {
    umount "$target" 2>&1 >/dev/null
    if [ ! -z "$squashref" -a -d "$base/obj/$squashref" ]; then
        rm -r "$base/obj/$squashref"
    fi
}
trap _cleanup KILL
trap _cleanup EXIT

squashref=$(echo "$ref $ancestor" | sha1sum | cut -d\  -f1)

target="$base/obj/$squashref/mnt"
mkdir -p "$base/obj/$squashref/mnt"

ancestorref=$("$base/ctl/refparse" "$ancestor")
if [ -f "$base/obj/$ancestorref/parent" ]; then
    cp "$base/obj/$ancestorref/parent" "$base/obj/$squashref/obj"
fi

"$base/ctl/mount" "$ref:$ancestor" "$target"

cp -rp "$base/obj/$squashref/mnt" "$base/obj/$squashref/fs"

if [ -z "$msg" ]; then
    msg="squashed layers $ref:$ancestor"
fi

"$base/ctl/commit" "$base/obj/$squashref" "$msg"
