#!/bin/bash
#
# tupper - A container image manager
#
# Copyright (c) 2018 Matt Ferris <matt@bueller.ca>
# Licensed under BSD 2-clause license
# github.com/mattferris/tupper/blob/master/License.txt
#

set -e

binpath="$PWD/ctl:~/containers/ctl:/usr/lib/tup"
if [[ ! -z "$TUP_BINPATH" ]]; then
    binpath=$TUP_BINPATH
fi

objpath="$PWD/obj:~/containers/obj:/var/lib/tup/obj"
if [[ ! -z "$TUP_OBJPATH" ]]; then
    objpath=$TUP_OBJPATH
fi

imgpath="$PWD:$PWD/img:~/containers/img:/var/lib/tup/img"
if [[ ! -z "$TUP_IMGPATH" ]]; then
    imgpath=$TUP_IMGPATH
fi

if [[ -z "$1" ]]; then
cat <<EOF >&2

usage: $(basename $0) <cmd> [ <args> ... ]

    checkout  Create an image from an existing object
    commit    Commit the changes in an image to an object
    lineage   List all the ancestors of an image or object
    mount     Mount an image or object
    rebase    Rebase an image to a different object
    refparse  Parse an object hash partial or tag
    revert    Revert an image to it's previous commit
    rm        Remove an object
    run       Boot or execute an image
    squash    Combine one or more related objects
    tag       Tag an object
    verify    Verify an object or lineage

EOF
exit 1
fi

cmd=$1
shift

IFS=":"
for path in $binpath; do
echo "$path/$cmd"
    if [[ -x "$path/$cmd" ]]; then
        exec "$path/$cmd" $@
    fi
done

echo "error: unknown command: $cmd" >&2
exit 1
